/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StreamRouteImport } from './routes/stream'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmailVerificationSuccessRouteImport } from './routes/email-verification-success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatChatIdRouteImport } from './routes/chat/$chatId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerificationSuccessRoute =
  EmailVerificationSuccessRouteImport.update({
    id: '/email-verification-success',
    path: '/email-verification-success',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-verification-success': typeof EmailVerificationSuccessRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stream': typeof StreamRoute
  '/verify-email': typeof VerifyEmailRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-verification-success': typeof EmailVerificationSuccessRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stream': typeof StreamRoute
  '/verify-email': typeof VerifyEmailRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email-verification-success': typeof EmailVerificationSuccessRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stream': typeof StreamRoute
  '/verify-email': typeof VerifyEmailRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-verification-success'
    | '/login'
    | '/register'
    | '/stream'
    | '/verify-email'
    | '/chat/$chatId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-verification-success'
    | '/login'
    | '/register'
    | '/stream'
    | '/verify-email'
    | '/chat/$chatId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/email-verification-success'
    | '/login'
    | '/register'
    | '/stream'
    | '/verify-email'
    | '/chat/$chatId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailVerificationSuccessRoute: typeof EmailVerificationSuccessRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StreamRoute: typeof StreamRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verification-success': {
      id: '/email-verification-success'
      path: '/email-verification-success'
      fullPath: '/email-verification-success'
      preLoaderRoute: typeof EmailVerificationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailVerificationSuccessRoute: EmailVerificationSuccessRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StreamRoute: StreamRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
